base_config: configs/base.yaml

experiment:
  name: roberta_swsr

data:
  train_path: data/processed/swsr/train.jsonl
  dev_path: data/processed/swsr/dev.jsonl
  test_path: data/processed/swsr/test.jsonl

model:
  backbone_name: hfl/chinese-roberta-wwm-ext
